### ISSUE TITLE
[BROKEN BUG ON DJANGO 2.1.7] - ImportError: cannot import name 'permalink'

### ISSUE THREAD

**Issue by willmendil** [aljosa/django-tinymce#246]
```
from django.db.models import permalink
ImportError: cannot import name 'permalink'
```

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.VERSION
(2, 1, 7, 'final', 0)
```

It seams permalink is not working in django 2.1.7. It worked in 2.0.3 ( have not tried in between).
It seems the issue is with **newsletter/models.py**. I saw this thread [https://openedx.atlassian.net/browse/PLAT-1435](https://openedx.atlassian.net/browse/PLAT-1435). But I am not sure how to modify the newsletter code 

(in case the page is broken here's what it said

> Use django.urls.reverse() instead. For example:

```
from django.db import models

class MyModel(models.Model):
    ...
    @models.permalink
    def url(self):
        return ('guitarist_detail', [self.slug])
```

> becomes:

```
from django.db import models
from django.urls import reverse

class MyModel(models.Model):
    ...
    def url(self):
        return reverse('guitarist_detail', args=[self.slug])
```

----
EDIT: 

Here's an example of how **newsletter/models.py** uses `@permalink`. If someone could convert this by using the solution above, I could try with the others:

   ```
 @permalink
    def get_absolute_url(self):
        return (
            'newsletter_detail', (),
            {'newsletter_slug': self.slug}
        )


@permalink
    def get_absolute_url(self):
        assert self.newsletter.slug
        assert self.message.slug

        return (
            'newsletter_archive_detail', (), {
                'newsletter_slug': self.newsletter.slug,
                'year': self.publish_date.year,
                'month': self.publish_date.month,
                'day': self.publish_date.day,
                'slug': self.message.slug
            }
        )

```

**Comment by willmendil** [comment]
Woops,wrong app
