### ISSUE TITLE
Uncaught ReferenceError: django is not defined ( init_tinymce.js:38 )

### ISSUE THREAD

**Issue by lives** [aljosa/django-tinymce#124]
Django 1.8 and django-tinymce==2.1.0.dev0

Unable to use django-tinymce in custom forms. 
Error : Uncaught ReferenceError: django is not defined ( init_tinymce.js:38 )

The "admin" test is ok, http://django-tinymce.readthedocs.org/en/latest/installation.html#testing

**Comment by Natim** [comment]
Does this fixes your issue? https://github.com/aljosa/django-tinymce/pull/108 or https://github.com/aljosa/django-tinymce/issues/102#issuecomment-75445878

**Comment by Natim** [comment]
Could you try last master, if it works for you I will make a bugfix release

**Comment by lives** [comment]
Natim, thank you for you answer.

Tested master 27407b3dea637900b2f8da9a553df858ac2f6c45 , but same error.

**Comment by eson-schulz** [comment]
I am having the same issue also using Django 1.8. I downgraded to Django-TinyMCE 1.5.2 as recommended by http://stackoverflow.com/questions/28643823/tinymce-for-django-is-not-loading-throwing-error-in-init 1.5.2 fixes the issue.

**Comment by lives** [comment]
Ok, it works with latest django-tinymce + a fix ( from master 27407b3dea637900b2f8da9a553df858ac2f6c45)

--- init_tinymce_27407b3dea637900b2f8da9a553df858ac2f6c45.js	2015-08-04 13:14:00.911348163 +0200
+++ init_tinymce.js	2015-08-04 13:14:10.187348075 +0200
@@ -35,4 +35,4 @@
       }, 0);
     }, true);
   });
-}( function () { return django && django.jQuery || jQuery }()));
+}( function (django) { return django && django.jQuery || jQuery }()));

**Comment by Natim** [comment]
I revert my commit, can you try current master? If it works I will release a new version of django-tinymce.

**Comment by eson-schulz** [comment]
Not sure about lives, but I pulled the current master; the code that was working with 1.5.2 stopped when I updated. The same "Uncaught ReferenceError: jQuery is not defined" issue.

**Comment by lives** [comment]
Working ok with master 4d6e78fa8d290524e7ab263161a80cdda2c0c96e , thanks.

**Comment by Natim** [comment]
Ok let's release a bugfix release and see how it goes.

**Comment by Natim** [comment]
@eson-schulz Make sure you include jQuery in your page and try https://github.com/aljosa/django-tinymce/releases/tag/2.0.3

**Comment by hiltonc** [comment]
I see this issue with django-tinymce 2.0.5. To repro:

1. Download and unzip https://www.dropbox.com/s/84kgv2eqn1cnf6i/django-tinymce-2.0.5-non-admin-broken.zip?dl=0
2. `pip install -r requirements.txt`
3. Run it and view the root page in your browser

Expected: TinyMCE awesomeness
Actual: JavaScript console error: "Uncaught ReferenceError: django is not defined"

**Comment by mattarchie** [comment]
@Natim Has that bugfix been released? I have django-tinymce 2.0.5 and I'm still getting the "django is not defined" error; however, when I add the change from #108 it works correctly. I see that in commit 3f68de1, the fix was altered (this commit's change is reflected in the code I have that gives the error). I'm not sure if the fact I'm using an older version of Django (1.4.1) would cause an issue with this, but it seems like the issue was fixed and then unfixed.

**Comment by dco5** [comment]
Is this working with django 1.8 and django-tinymce 2.0.5?? I am getting
Uncaught ReferenceError: django is not defined           init_tinymce.js:38

**Comment by Natim** [comment]
Does somebody want to fix this and file a PR? I will merge it and release 2.0.6.

**Comment by mattarchie** [comment]
@Natim I was about to summit a PR reverting 3f68de1, to bring back the fix from #108 but I tested the change and realized that while it solves my own problem, it creates another. The current version of init_tinymce.js, works with admin pages, but not with non-admin ones. After the revert, the code works with non-admin pages, but not admin ones. I then used your suggestion in #108 of passing in the django parameter another time, but this gets us back to only admin pages working.

The following two versions of init_tinymce.js:38 make admin pages work, but not non-admin ones:
```
}(django && django.jQuery || jQuery));
```
and
```
}( function(django) { return django && django.jQuery || jQuery}(django)));
```

While this version makes non-admin pages work, but not admin ones:
```
}( function(django) { return django && django.jQuery || jQuery}()));
```
This gives the following error on the admin page in the test app provided by django-tinymce:
```
Uncaught TypeError: $ is not a function init_tinymce.js:18
(anonymous function) @ init_tinymce.js:18
(anonymous function) @ init_tinymce.js:38
```

**Comment by mattarchie** [comment]
Is the purpose of the django && django.jQuery to make sure that you use the jQuery version in the django namespace instead of the jQuery version pointed to by the global jQuery variable? Whether that's the case or not, this should work to replace `}(django && django.jQuery || jQuery));` without breaking the preference for django.jQuery if it exists:
```
}((typeof django === 'undefined' || typeof django.jQuery === 'undefined') && jQuery || django && django.jQuery));
```
I will create a PR with this version because it works for me on both admin and non-admin pages.

**Comment by Natim** [comment]
A fix has been released as per django-tinymce 2.0.6 can you guys check it and validate that it fixes your problem?

Thanks @mattarchie for fixing this.

**Comment by hiltonc** [comment]
I just had a chance to try this out. Works great, thank you!

**Comment by Natim** [comment]
Thank you for the feedback @hiltonc :)
